"""empty message

Revision ID: e853894d632e
Revises: None
Create Date: 2016-10-10 16:27:26.358819

"""

# revision identifiers, used by Alembic.
revision = 'e853894d632e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vote_user', sa.Column('vote_count', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vote_user', 'vote_count')
    ### end Alembic commands ###
